# Generated by Django 5.2.1 on 2025-05-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcontact",
            name="patient_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientcontact",
            name="patient_height",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patientcontact",
            name="patient_sex",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="patientcontact",
            name="patient_weight",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
