# Generated by Django 5.2.1 on 2025-05-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_patientcontact_patient_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthdata",
            name="blood_pressure",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
