# Generated by Django 5.2.1 on 2025-06-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_device_healthdata_device_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
